version: "3.9"

services:
  backend:
    build: ./JobManager
    container_name: jobmanager-app
    ports:
      - "8080:8080"

  frontend:
    build: ./site
    container_name: jobmanager-site
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    depends_on:
      - backend
