version: "3.9"

services:
  backend:
    build: ./JobManager
    container_name: jobmanager-app
    volumes:
      - ./JobManager/src:/app/src
      - ./JobManager/build.gradle:/app/build.gradle
      - ./JobManager/settings.gradle:/app/settings.gradle
    ports:
      - "8080:8080"

  frontend:
    build: ./site
    container_name: jobmanager-site
    volumes:
      - ./site/src:/app/src
      - ./site/public:/app/public
      - ./site/package.json:/app/package.json
      - ./site/package-lock.json:/app/package-lock.json
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    command: npm run dev
    depends_on:
      - backend
