FROM node:20-alpine
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the source code
COPY . .

# Expose port
EXPOSE 3000

# Run Next.js in dev mode (with hot-reload)
CMD ["npm", "run", "dev"]
